[functions]
included_files = ["functions/PDFS/ThomasDoyleResume.pdf"]
[build]
command="npm run build"
functions="functions"
publish="build"
[[redirects]]
from="/api/*"
to="/.netlify/functions/:splat"

    

    